# Generated by Django 5.2.1 on 2025-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="书名"),
                ),
                ("author", models.CharField(max_length=32, verbose_name="作者")),
                ("price", models.FloatField(verbose_name="价格")),
            ],
        ),
    ]
