# Generated by Django 5.2.1 on 2025-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinfo",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="封面"
            ),
        ),
    ]
