# Generated by Django 5.2.1 on 2025-05-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="quantity",
            new_name="number",
        ),
    ]
