# Generated by Django 5.2.1 on 2025-05-21 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_quantity_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="下单日期"
            ),
        ),
    ]
